function generate() {

let topic = document.getElementById("topic").value.trim();

if(topic==""){
    alert("Enter a topic!");
    return;
}

const result = document.getElementById("result");

result.innerHTML = "🧠 Analyzing Topic...";

setTimeout(()=>{

result.innerHTML = `
<div class="card" style="width:90%;max-width:700px;margin:auto;">

<h2>${topic}</h2>

<h3>📖 Summary</h3>
<p>
${topic} is an important concept. These notes are generated by Comback AI.
</p>

<h3>⭐ Key Points</h3>

<ul>
<li>Important Point 1</li>
<li>Important Point 2</li>
<li>Important Point 3</li>
</ul>

<h3>❓ MCQs</h3>

<p>1. Sample MCQ</p>
<p>2. Sample MCQ</p>

<h3>⚡ 30 Second Revision</h3>

<p>
Quick revision of ${topic}
</p>

</div>
`;

},2000);

}

}

function typeEffect(html,element){

element.innerHTML="";

let i=0;

let interval = setInterval(()=>{

element.innerHTML =
html.slice(0,i);

i++;

if(i > html.length){
    clearInterval(interval);
}

},10);

}