function generate(){

let topic =
document.getElementById("topic").value.trim();

if(topic===""){
    alert("Enter a topic first!");
    return;
}

const result =
document.getElementById("result");

let loadingMessages = [
"🧠 Analyzing Topic...",
"📚 Generating Notes...",
"⚡ Creating Revision...",
"✅ Finalizing Output..."
];

let step = 0;

result.innerHTML = loadingMessages[0];

let loader = setInterval(()=>{

step++;

if(step < loadingMessages.length){
    result.innerHTML = loadingMessages[step];
}
else{

clearInterval(loader);

let output = `
<h2>${topic}</h2>

<h3>📖 Summary</h3>
<p>
${topic} is an important topic.
These notes are generated by Comback AI.
</p>

<h3>⭐ Key Points</h3>
<ul>
<li>Important Point 1</li>
<li>Important Point 2</li>
<li>Important Point 3</li>
</ul>

<h3>❓ MCQs</h3>
<p>1. Example MCQ?</p>
<p>2. Example MCQ?</p>

<h3>⚡ 30 Second Revision</h3>
<p>
Quick revision of ${topic}.
</p>
`;

typeEffect(output,result);

}

},1000);

}

function typeEffect(html,element){

element.innerHTML="";

let i=0;

let interval = setInterval(()=>{

element.innerHTML =
html.slice(0,i);

i++;

if(i > html.length){
    clearInterval(interval);
}

},10);

}